apiVersion: v1
kind: Pod
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  containers:
  - image: jaegertracing/all-in-one:1.53
    name: jaeger
    env:
      - name: COLLECTOR_OTLP_ENABLED
        value: "true"
    ports:
      # UI
      - containerPort: 16686
        protocol: TCP
      - containerPort: 4317
        protocol: TCP
      - containerPort: 4318
        protocol: TCP
