apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger
spec:
  ports:
  - name: 16686-web
    port: 16686
  - name: grpc
    port: 4317
  - name: http
    port: 4318
  selector:
    app: jaeger
